### ISSUE TITLE
Spawn egg textures

### ISSUE THREAD

**Issue by Sumanuil** [eccentricdevotion/New-Zealand-Natives-Addon#9]
Spawn egg textures don't seem to be working in 1.20.51. Some or all of them don't show up, but which ones seems to vary between worlds. Some worlds, it's just one or two, others, all of them are broken. I noticed that item_texture.json is missing some, but adding them in didn't fix anything.

**Comment by eccentricdevotion** [comment]
Seems to be fixed in the latest build for me

<img width="1552" alt="Screenshot 2024-01-27 at 8 26 52 PM" src="https://github.com/eccentricdevotion/New-Zealand-Natives-Addon/assets/1841924/9ae1fe86-f064-4894-bff5-588b814a9906">

https://github.com/eccentricdevotion/New-Zealand-Natives-Addon/releases/tag/natives

**Comment by eccentricdevotion** [comment]
Make sure you completely remove the packs from your bedrock installation and all worlds before importing and installing the new one

**Comment by Sumanuil** [comment]
It's fixed, but I had to remove and reinstall it about four times before they all showed up.

**Comment by eccentricdevotion** [comment]
Yeah that's typical of bedrock I've found
